name: generate pacman

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia à meia-noite
  workflow_dispatch:     # permite rodar manualmente
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: generate pacman (snake style)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Caio-Lessaa
          outputs: |
            dist/pacman.svg?palette=github-dark&color_snake=yellow

      - name: Push generated files
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
          force_orphan: true
