name: generate animation

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia à meia-noite
  workflow_dispatch:     # permite rodar manualmente
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: generate pacman contribution grid snake
        uses: Platane/snk@v3
        with:
          github_user_name: Caio-Lessaa
          outputs: |
            dist/pacman-contribution-graph.svg?palette=github-dark
            dist/pacman-contribution-graph-dark.svg?palette=github-dark

      - name: Push generated files
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
